import type { Metadata } from "next";
import {
  //clerk loaded sm loading tambahan krn clerk default behaviour nya ngeblink
  ClerkLoaded,
  ClerkLoading,
  ClerkProvider,
  // UserButton,
  // SignInButton,
  // SignedIn,
  // SignedOut,
} from "@clerk/nextjs";

import "../globals.css";
import LeftSideBar from "@/components/layout/LeftSideBar";
import { TopBar } from "@/components/layout/TopBar";
import { ToasterProvider } from "@/lib/ToasterProvider";

export const metadata: Metadata = {
  title: "Ahlan Coding Dashboard",
  description: "Generated by ahlan coding",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          {/* clerkloading */}
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl">
              <img
                src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1a462d05-03f4-469b-b30e-19af4adaa553/dflflsu-ebde2b43-7faf-4a4b-8f9a-ff94857caf9f.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFhNDYyZDA1LTAzZjQtNDY5Yi1iMzBlLTE5YWY0YWRhYTU1M1wvZGZsZmxzdS1lYmRlMmI0My03ZmFmLTRhNGItOGY5YS1mZjk0ODU3Y2FmOWYuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.1TmLZNjYIB68XdiwEF1_6QG5sDVwjBeI5DY7aMdpBTg"
                alt=""
              />
            </div>
          </ClerkLoading>

          {/* clerkloaded */}
          {/* kalo clerk loaded baru kita munculin isi web kita */}
          <ClerkLoaded>
            <ToasterProvider />
            {/* container webpage, flexbox, kalau lg jd flex-col */}
            <div className="flex max-lg:flex-col text-grey-1">
              <LeftSideBar />
              <TopBar />
              {children}
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
